before_install:
  - pip install --user pysam
  - wget https://github.com/vcftools/vcftools/tarball/master -O master_vcftools.tar.gz
  - tar -xzvf master_vcftools.tar.gz
  - cd vcftools* && ./autogen.sh && ./configure --prefix=/usr && make && sudo make install

cache: pip

script: 
  - python jared/tests.py
#  - python andrew/vcf_tests.py
