sudo: required

language: python
python:
  - "2.7"
  - "3.6"

before_install:
  - pip install -r requirements.txt
  - ./install_executables.sh
  - sudo apt-get install -y r-base

cache: pip

script:
  - sh run_jared_tests.sh
  - sh run_andrew_tests.sh
