before_install:
  - pip install --user pysam
  - wget https://github.com/vcftools/vcftools/tarball/master -O vcftools.tar.gz
  - tar -xzvf vcftools.tar.gz
  - pushd vcftools && ./configure --prefix=/usr && make && sudo make install && popd

cache: pip

script: 
  - python jared/tests.py
#  - python andrew/vcf_tests.py
