before_install:
  - pip install --user pysam
  - wget https://github.com/vcftools/vcftools/tarball/master -O master_vcftools.tar.gz
  - tar -xzvf master_vcftools.tar.gz
  - cd vcftools* && ./autogen.sh --silent && ./configure --prefix=/usr --silent && make --silent && sudo make install && cd ..

cache: pip

script: 
  - python jared/tests.py
  - cd andrew && python vcf_tests.py && cd ..
