language: python
python: 
  - "2.7"
  - "3.6"

before_install:
  - pip install --user -r requirements.txt
  - ./install_executables.sh

install:
  - pip install -r requirements.txt

cache: pip

script: 
  - sh run_jared_tests.sh
  - cd andrew && python andrew_tests.py && cd ..