sudo: required

language: python
python:
  - "2.7"
  - "3.6"

before_install:
  - ./install_executables.sh

install:
  - pip install -r requirements.txt

cache: pip

script:
  - sh run_jared_tests.sh
  - sh run_andrew_tests.sh
