sudo: required

language: python
python:
  - "2.7"
  - "3.6"

before_install:
  - ./install_R.sh
  - pip install -r requirements.txt
  - ./install_executables.sh

addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base

cache: pip

script:
  - sh run_jared_tests.sh
  - sh run_andrew_tests.sh
