sudo: required

language: python
python:
  - "2.7"
  - "3.6"

before_install:
  - sudo add-apt-repository "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -sc)/"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo add-apt-repository ppa:marutter/rdev
  - sudo apt-get update
  - sudo apt-get install r-base
  - pip install -r requirements.txt
  - ./install_executables.sh

cache: pip

script:
  - sh run_jared_tests.sh
  - sh run_andrew_tests.sh
