language: python
python: 
  - "2.7"
  - "3.6"

before_install:
  - pip install --user -r requirements.txt
  - wget https://github.com/vcftools/vcftools/tarball/master -O master_vcftools.tar.gz
  - tar -xzvf master_vcftools.tar.gz
  - cd vcftools* && ./autogen.sh --silent && ./configure --prefix=/usr --silent && make --silent && sudo make install && cd ..

cache: pip

script: 
  - sh run_jared_tests.sh
  - cd andrew && python vcf_tests.py && cd ..
